trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  tag: "$(Build.BuildNumber)"
  tagArm: "$(Build.BuildNumber)-arm64"

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'fallenwood-docker'
    repository: 'fallenwood-echo'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile.arm64'
    tags: |
      $(tagArm)
